#!/bin/sh
python update_analysis.py 3
python update_analysis.py 4
python update_analysis.py 5
python update_analysis.py 6
python update_analysis.py 7
python update_analysis.py 8
python update_analysis.py 9
python update_analysis.py 10
python update_analysis.py 11
python update_analysis.py 12
python update_analysis.py 13
python update_analysis.py 14
python update_analysis.py 15
python update_analysis.py 16
python update_analysis.py 17
python update_analysis.py 18
python update_analysis.py 19
python update_analysis.py 20
python update_analysis.py 21
python update_analysis.py 22
python update_analysis.py 23
python update_analysis.py 24
python update_analysis.py 25
python update_analysis.py 26
python update_analysis.py 27
python update_analysis.py 28
python update_analysis.py 29
python update_analysis.py 30
python update_analysis.py 31
python update_analysis.py 32
python update_analysis.py 33
python update_analysis.py 34
python update_analysis.py 35
python update_analysis.py 36
python update_analysis.py 37
python update_analysis.py 38
python update_analysis.py 39
python update_analysis.py 40
python update_analysis.py 41
python update_analysis.py 42
python update_analysis.py 43
python update_analysis.py 44
python update_analysis.py 45
python update_analysis.py 46
python update_analysis.py 47
python update_analysis.py 48
python update_analysis.py 49
python update_analysis.py 50
exit 1